# Spring properties
spring:
  application:
     name: sync-registry-service  # Service registers under this name

# Map the error path to error template (for Thymeleaf)
error:
  path: /error

# HTTP Server
server:
  port: 1111   # HTTP (Tomcat) port